version: '3.3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/karbitrage
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=mypassword
      - DATABASE_DRIVER=org.postgresql.Driver
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: karbitrage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
      - /karbitrage-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
